apps/usersApp/urls.py
from django.urls import path

from . import views

app_name = 'usersApp'
urlpatterns = [
    path('signup/', views.RegistrationView.as_view(), name='signup'),
    
    # Mentor Profiles 
    path('mentor_detail/', views.MentorProfileDetailView.as_view(), name='mentor_detail'),
    path('mentor/public/profile/<slug:slug>/', views.MentorPublicProfileView.as_view(), name='mentor_public_profile'),
    path('mentor/profile/update/', views.MentorUpdateProfileView.as_view(), name='mentor_update_profile'),

    # Tertiary Profiles 
    path('tertiary_detail/', views.TertiaryProfileDetailView.as_view(), name='tertiary_detail'),
    path('tertiary/public/profile/<slug:slug>/', views.TertiaryPublicProfileView.as_view(), name='tertiary_public_profile'),
    path('tertiary/profile/update/', views.TertiaryProfileUpdateView.as_view(), name='tertiary_update_profile'),

    # Non Tertiary Profiles
    path('nontertiary_detail/', views.NonTertiaryProfileDetailView.as_view(), name='nontertiary_detail'),
    path('nontertiary/public/profile/<slug:slug>/', views.NonTertiaryPublicProfileView.as_view(), name='nontertiary_public_profile'),
    path('nontertiary/profile/update/', views.NonTertiaryProfileUpdateView.as_view(), name='nontertiary_profile_update'),

    # Alumni Profiles 
    path('alumni_detail/', views.AlumniProfileDetailView.as_view(), name='alumni_detail'),
    path('alumni/public/profile/<slug:slug>/', views.AlumniPublicProfileView.as_view(), name='alumni_public_profile'),
    path('alumni/profile/update/', views.AlumniProfileUpdateView.as_view(), name='alumni_profile_update'),

]

logos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from .views import ping

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ping/", ping, name="ping"),
    path("accounts/", include("allauth.urls")),
    path("", include("apps.usersApp.urls", namespace="usersApp")),
    path("", TemplateView.as_view(template_name="base.html"), name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logos/views.py
from django.http import JsonResponse


def ping(request):
    data = {"ping": "pong!"}

    return JsonResponse(data)

logos/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/5c55136842.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/section.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    
    {% block extrahead %}
        
    {% endblock extrahead %}
        
    <title>Logos Portal</title>
    
</head>
<body>
    <header>
        <nav>  
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="fas fa-bars"></i>
            </label>
            <a href="{% url 'home' %}" class="logo">
                <img src="{% static 'images/logo.png' %}" alt="">
            </a>
            <ul>
                <!--Non tertiary-->
            {% if user.is_authenticated and user.user_type == "NonTertiary" %}
            <a href="{% url 'usersApp:nontertiary_detail' %}">Your Profile</a> 
            <a href="{% url 'account_logout' %}">Logout</a>
           
            <!--Tertiary Menu-->
            {% elif user.is_authenticated and user.user_type == "Tertiary" %}
            <a href="{% url 'usersApp:tertiary_detail' %}">Your Profile</a> 
            <a href="{% url 'account_logout' %}">Logout</a>

             <!--Alumni Menu-->
             {% elif user.is_authenticated and user.user_type == "Alumni" %}
             <a href="{% url 'usersApp:alumni_detail' %}">Your Profile</a> 
             <a href="{% url 'account_logout' %}">Logout</a>
            <!--Admin-->
            {% elif user.is_authenticated and user.is_superuser %}
             <a href="{% url 'admin:index' %}">Admin Panel</a> 
              <!--Mentor-->
            {% elif user.is_authenticated and user.user_type == "Mentor" %}
            <a href="{% url 'usersApp:mentor_detail' %}">Your Profile</a> 
            <a href="{% url 'account_logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'account_login' %}">Login</a>
            <li><a href="#">Newsletter</a></li>
                <li><a href="#home">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#services">Logos Team</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="#feedback">Logos Community</a></li>
            {% endif %}            
            </ul>
        </nav>
    </header>
    
    {% block content %}   
    <!--Sections-->
<div class="containers">
<!--Home-->
<section id="home">
    <h2 data-aos="fade-down"data-aos-easing="linear"data-aos-duration="1500">
        
        Welcome To Logos Portal.
    </h2>
</section>

    <!--About logos portal-->
<section id="about">
    <h1 data-aos="fade-down"
    data-aos-easing="linear"
    data-aos-duration="1500">About</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, similique delectus eum nihil harum soluta deserunt ab amet sunt debitis adipisci error, quasi quos dolorum sapiente quod dolore vitae consectetur!
        Animi officia ex a architecto dicta doloremque, nemo, voluptatum eos ipsa excepturi non atque. Natus facere voluptatibus enim, perferendis cum rerum recusandae illo, doloremque consequatur quis, eaque itaque ad eos.
        Doloribus aspernatur qui corrupti, ea id porro impedit consectetur numquam ipsum est, necessitatibus delectus praesentium laudantium quas quidem atque laboriosam. Consectetur pariatur magnam dignissimos non, minima nostrum sed repudiandae eaque!
        Architecto accusantium saepe sapiente. Doloribus mollitia debitis culpa dolorum ratione tempora, id aliquid similique dolores deserunt, qui placeat tenetur cum exercitationem! Corrupti, praesentium officiis. Sapiente laudantium nobis ad ex nihil.
        Iusto sint sed similique doloribus ducimus incidunt velit laborum, pariatur nesciunt exercitationem optio, sequi illo ab. Ipsa facere ipsum laudantium culpa obcaecati et impedit non numquam eius enim, dignissimos consectetur?</p>
</section>
 
<!--Meet the Logos team-->
<section id="services">
    <h1 data-aos="fade-down"
    data-aos-easing="linear"
    data-aos-duration="1500">Logos Team</h1>
    <div class="container-team">
        <!--Team one-->
        <div class="our-team">
            <div class="pic">
                <img src="{% static 'images/Grad.jpg' %}" alt="">
            </div>
            <div class="team-content">
                <h3 class="title">Hilda</h3>
                    <span class="post">Co-ordinator</span>
            </div>
            <ul class="social">
                <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li> 
            </ul>
            </div>
        <!--Team Two-->
        <div class="our-team">
            <div class="pic">
                <img src="{% static 'images/Grad.jpg' %}" alt="">
            </div>
            <div class="team-content">
                <h3 class="title">Paul</h3>
                    <span class="post">Director</span>
            </div>
            <ul class="social">
                <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li> 
            </ul>
            </div>
        <!--Team three-->
        <div class="our-team">
            <div class="pic">
                <img src="{% static 'images/Grad.jpg' %}" alt="">
            </div>
            <div class="team-content">
                <h3 class="title">Jane</h3>
                    <span class="post">Social Justice</span>
            </div>
                <ul class="social">
                    <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li> 
                </ul>
            </div>
        </div>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates est obcaecati doloribus voluptatum soluta rerum culpa consequuntur odio quod amet sint sit, laudantium nihil deleniti exercitationem atque quos ratione. Enim?
        Magnam reprehenderit atque accusamus fugit in, culpa iure laborum amet, quae facilis tenetur deserunt sed error esse veritatis! Iusto laudantium inventore, ratione ipsa cupiditate non temporibus alias excepturi? Non, ullam.
        Similique asperiores tempora, placeat molestiae, veniam dolores saepe ad enim blanditiis accusantium aspernatur maxime temporibus laborum recusandae soluta eos unde. Enim est architecto reprehenderit? Corrupti debitis ullam iusto tempora eveniet.
        Accusantium laborum ipsum provident quidem, tempore, nulla esse, iste vero adipisci debitis sint? Totam corrupti quae, dignissimos perspiciatis amet placeat culpa tenetur nam dolor fugit eligendi vel tempora asperiores facilis!
        In tempora vel architecto illo quas natus dolorum placeat minima provident, quam error velit a, non eaque officiis. Itaque, dolore suscipit temporibus facere fugiat incidunt excepturi exercitationem quo facilis necessitatibus!</p>

</section>
   
<!--Contact us-->  
<section id="contact">
    <h1 data-aos="fade-down"
    data-aos-easing="linear"
    data-aos-duration="1500">Contact</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus ea iste magni perferendis unde officia exercitationem dolorum omnis corrupti sequi dolorem iure, eos doloremque illum alias fugiat quo quaerat dicta?
        Harum numquam eveniet expedita officiis? Et, error? Amet placeat nostrum eaque. In, perferendis rerum officia facilis incidunt iure ipsam cumque ex eius, necessitatibus dignissimos dolor. Necessitatibus cum neque architecto explicabo.
        Saepe sapiente voluptas sunt. Id aliquam modi dignissimos animi commodi et maxime delectus iste velit. Sapiente reiciendis consectetur recusandae, perferendis voluptatum unde fugiat nulla perspiciatis saepe amet? Molestiae, nihil ad?
        Vel ducimus officia possimus amet sequi! Nulla, perspiciatis? Sapiente dolores ea distinctio assumenda! Commodi tempore at accusantium vero quaerat esse dignissimos. Nulla quam aliquam illum cumque nostrum voluptatum, enim numquam.
        Iste officiis illum autem molestias eum rem ea magni quos dolor aliquam! Sunt eius dicta quam! Deserunt nostrum commodi quis quia, soluta quibusdam doloremque? Possimus magni ullam qui vel non!</p>
</section>
    
<!--Logos community-->
<section id="feedback">
    <h1 data-aos="fade-down"
    data-aos-easing="linear"
    data-aos-duration="1500">Logos Community</h1>
    <div class="container-fluid" id="my-scrollbar">
        <div class="row">
            <div class="col-xl-4">
                <div class="service-box">
                    <span class="icon">
                        <i class="fa fa-graduation-cap" aria-hidden="true"></i>
                    </span><h4>Scholars</h4>
                    <h5>
                        Our scholars range from primary, 
                        secondary as well as university. 
                        As such, the scholars are grouped
                        into non tertiary and tertiary scholars. 
                        Our scholars come from the less 
                        priviledge families in the slums.
                    </h5>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="service-box">
                    <span class="icon">
                        <img src="{% static 'images/mentor.png' %}" alt="">
                    </span><h4>Mentors</h4>
                    <h5>
                        Our mentors are an integral part of our 
                        program.These are men and women who have
                        volounteered to help our young scholars
                        by offering emotional support as well as 
                        courieer guidance. 
                    </h5>
                </div>
            </div>
            <div class="col-xl-4">
                <div class="service-box">
                    <span class="icon">
                        <img src="{% static 'images/Alumnis.png' %}" alt="">
                    </span>
                        <h4>Alumnis</h4>
                    <h5>
                        Our alumnis are the strongest evidence
                        that we are touching lives. These are young
                        people who have gone through Logos scholarship
                        from primar, highschool all the way to the
                        University.
                    </h5>
                </div>
            </div>
        </div>
    </div>
</section>
</div>
    {% endblock content %}
<footer class="footer">
    <!--On the left-->
    <div class="footer-left">
        <img src="{% static 'images/logo.png' %}" alt="">
            <ul class="social-icons">
                <li><i class="fab fa-facebook-f"></i></li>
                <li><i class="fab fa-twitter"></i></li>
                <li><i class="fab fa-google"></i></li>
                <li><i class="fab fa-linkedin-in"></i></li>
            </ul>
        </div>
<!--On the right-->
    <ul class="footer-right">
        <li>
            <h2>Useful links</h2>
            <ul class="boxes">
                <li><a href="#">Newsletter</a></li>
                <li><a href="#home">Home</a></li>
                <li><a href="#about">About Us</a></li>
                <li><a href="#services">Logos Team</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="#feedback">Logos Community</a></li>
            </ul>
        </li>
    </ul>
    <div class="footer-bottom">
        <p>All Right reserved &copy;kennankole 2020</p>
    </div>
</footer>


<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
<script src="https://apis.google.com/js/platform.js" async defer></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->
<script src="https://use.fontawesome.com/ec174cb989.js"></script>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rellax/1.12.1/rellax.min.js"></script>
<script type="text/javascript">
    var rellax = new Rellax('.rellax')
</script>
<script>
    AOS.init();
</script>
    <!--  -->
</body>
</html>